services:

  nginx:
    environment:
      - FULLCHAIN_FILE=/run/secrets/server_cert
      - PRIVKEY_FILE=/run/secrets/server_key
    secrets:
      - server_cert
      - server_key
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - api-gateway
    ports:
      - "4443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - pong:/var/www/html/pong
    restart: always

  api-gateway:
    container_name: api-gateway
    secrets:
      - api_cert
      - api_key
    build: requirements/api-gateway
    depends_on:
      - auth-service
      - service-b
    
  sqlite-web:
    build: requirements/sqlite-web
    container_name: sqlite-web
    ports:
      - "9090:9090"
    depends_on:
      - auth-service
    restart: always

  auth-service:
    container_name: auth-service
    build: requirements/auth-service

  service-b:
    container_name: service-b
    build: requirements/service-b

networks:
  default:
    name: transcendence-network
    driver: bridge

volumes:
  pong:
    driver: local
    driver_opts:
      type: none
      device: $PWD/srcs/data/pong
      o: bind

secrets:
  server_cert:
    file: ./secrets/cert.pem
  server_key:
    file: ./secrets/key.pem
  api_cert:
    file: ./secrets/apicert.pem
  api_key:
    file: ./secrets/apikey.pem

