services:

  nginx:
    environment:
      - FULLCHAIN_FILE=/run/secrets/server_cert
      - PRIVKEY_FILE=/run/secrets/server_key
    secrets:
      - server_cert
      - server_key
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - api-gateway
    ports:
      - "4443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - transcendence:/var/www/html/transcendence
    restart: always

  website:
    build: docker/website/.
    container_name: website
    ports:
      - "3000:3000"
    networks:
      ft_transcendence:
    volumes:
      - ./docker/website/public:/app/public
      - ./docker/website/typescript:/app/typescript
      - ./docker/website/backend/server.js:/app/server.js
    command: sh -c "npm run build && node server.js"
    restart: always

volumes:
  transcendence:
    driver: local
    driver_opts:
      type: none
      device: data/transcendence
      o: bind

secrets:
  server_cert:
    file: ./secrets/cert.pem
  server_key:
    file: ./secrets/key.pem

