version: "3.8"

services:
  nginx:
    build: docker/nginx/.
    container_name: nginx
    depends_on:
      - website
    ports:
      - "443:443"
    volumes:
      - website:/usr/share/nginx/html
    env_file:
      - .env
    networks:
      ft_transcendence:
    restart: always

  website:
    build: docker/website/.
    container_name: website
    ports:
      - "3000:3000"
    networks:
      ft_transcendence:
    volumes:
      - ./docker/website/public:/app/public
      - ./docker/website/typescript:/app/typescript
      - ./docker/website/server.js:/app/server.js
    command: sh -c "tsc --watch & node server.js"
    # command: sh -c "npm run build && node server.js"
    restart: always

volumes:
  website:
    name: website

networks:
  ft_transcendence:

