services:

  nginx:
    environment:
      - FULLCHAIN_FILE=/run/secrets/server_cert
      - PRIVKEY_FILE=/run/secrets/server_key
    secrets:
      - server_cert
      - server_key
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - api-gateway
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - transcendence:/var/www/html/transcendence
    restart: always

  api-gateway:
    build: requirements/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - service-a
      - service-b

  service-a:
    build: requirements/service-a
    expose:
      - "3001"

  service-b:
    build: requirements/service-b
    expose:
      - "3002"

networks:
  default:
    name: transcendence-network
    driver: bridge

volumes:
  transcendence:
    driver: local
    driver_opts:
      type: none
      device: data/transcendence
      o: bind

secrets:
  server_cert:
    file: ./secrets/cert.pem
  server_key:
    file: ./secrets/key.pem

